language: java

jdk:
  - openjdk8

before_install:
  - git clone https://github.com/mpassid/shibboleth-idp-authn-discovery -b 0.9.5
  - mvn install -f shibboleth-idp-authn-discovery/pom.xml

script:
  mvn clean package

after_failure:
  - cat target/surefire-reports/*.txt

after_success:
  - mvn clean cobertura:cobertura coveralls:report
